#!/bin/bash

DIR='./src/common/'

export GO111MODULE=on

for v in `ls $DIR` 
do
	if [ -d $DIR$v ]
	then
		echo 'build '$v
		cd $DIR$v
		go get
		go build
		cd ../../../
	fi
done

cd ./src/server
go build
echo 'build server'

cd ..
go build
echo 'build server'

echo 'build over'
